import TrackingCompletedImage from "../../../assets/images/trackingCardImage.png";

export const items = [
  {
    id: 1,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 2,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 3,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 4,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 5,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 6,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 7,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
  {
    id: 8,
    ModelName: "Blender: Crush 3",
    ModelNumber: 1397438432,
    JobID: "BMG 174",
    SentFor: "Repair",
    ComplaintStage: "Pending",
    ComplaintDate: "24th March, 2024",
    trackImage: TrackingCompletedImage,
  },
];
